cp /usr/local/nginx/html/selfdev_can_sale/app/Exceptions/BusinessException.php /usr/local/nginx/html/sale/app/Exceptions/BusinessException.php
cp /usr/local/nginx/html/selfdev_can_sale/app/Http/Controllers/Lptapp/CouponActivityController.php /usr/local/nginx/html/sale/app/Http/Controllers/Lptapp/CouponActivityController.php
cp /usr/local/nginx/html/selfdev_can_sale/app/Http/Controllers/Lptapp/CouponActivityUserController.php /usr/local/nginx/html/sale/app/Http/Controllers/Lptapp/CouponActivityUserController.php
cp /usr/local/nginx/html/selfdev_can_sale/app/Models/LptApp/CouponActivity.php /usr/local/nginx/html/sale/app/Models/LptApp/CouponActivity.php
cp /usr/local/nginx/html/selfdev_can_sale/app/Models/LptApp/CouponActivityBatch.php /usr/local/nginx/html/sale/app/Models/LptApp/CouponActivityBatch.php
cp /usr/local/nginx/html/selfdev_can_sale/app/Models/LptApp/CouponActivityUser.php /usr/local/nginx/html/sale/app/Models/LptApp/CouponActivityUser.php
cp /usr/local/nginx/html/selfdev_can_sale/app/Services/CouponActivityService.php /usr/local/nginx/html/sale/app/Services/CouponActivityService.php
cp /usr/local/nginx/html/selfdev_can_sale/config/apidoc.php /usr/local/nginx/html/sale/config/apidoc.php
cp /usr/local/nginx/html/selfdev_can_sale/config/app.php /usr/local/nginx/html/sale/config/app.php
cp /usr/local/nginx/html/selfdev_can_sale/storage/responses/coupon/batch-list.json /usr/local/nginx/html/sale/storage/responses/coupon/batch-list.json
cp /usr/local/nginx/html/selfdev_can_sale/storage/responses/coupon/coupon-activity-list.json /usr/local/nginx/html/sale/storage/responses/coupon/coupon-activity-list.json
cp /usr/local/nginx/html/selfdev_can_sale/storage/responses/coupon/coupon-activity-user-list.json /usr/local/nginx/html/sale/storage/responses/coupon/coupon-activity-user-list.json
cp /usr/local/nginx/html/selfdev_can_sale/ /usr/local/nginx/html/sale/
cp /usr/local/nginx/html/selfdev_can_sale/app/Http/Controllers/Lptapp/AdminMiniOrderController.php /usr/local/nginx/html/sale/app/Http/Controllers/Lptapp/AdminMiniOrderController.php
